### ISSUE TITLE
Poor Performance As Each Event is Treated Individually

### ISSUE THREAD

**Issue by b1scuit-thi3f** [z1pti3/jimiPlugin-occurrence#1]
Occurrence should bulk events together in cache, so that events can be updated in bulk on the destruction of the flow.

**Comment by ghost** [comment]
Added some adjustments to the way occurrence works with the database. This latest push is not backwards compatible with the old style of occurrence flows.

Stress tested the plugin with 10,000 occurrences performance is within 15 seconds however it does result in a race condition due to the use of "dontCheck=True" which means when an object is added to the cache, if the cache is refreshed before the commit to the database has completed then the object is removed from cache and the object recreated. - Need to add some additional checks for this or increase the cache time to be in-line with lull time.

``` 
foundOccurrence = cache.globalCache.get("occurrenceCacheMatch",match,getOccurrenceObject,dontCheck=True)
```

**Comment by ghost** [comment]
Due to the way jimi Cache works it means that Occurrence is not limited by memory size as it will load them into a single object that can be over the max size. The use of insert on the cache also means that the match cache will never be checked for memory usage.

**Comment by ghost** [comment]
More bug fixes added to make this as fast as possible. 

jimi core cache now disables memory checks since b152283592a5f0de4c9e597df314be2e94ae154c

The jimi cache feature did not really prevent memory issues or excessive memory, it is better to handle this within plugins and/or by making sure systems are sized correctly for the workloads to preform.
